apiVersion: apps/v1
kind: Deployment
metadata:
  name: revenue-calculator
  labels:
    app: revenue-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: revenue-calculator
  template:
    metadata:
      labels:
        app: revenue-calculator
    spec:
      containers:
      - name: revenue-calculator
        image: revenue-calculator:${IMAGE_TAG:-latest}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: revenue-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: revenue-db-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: revenue-calculator-service
spec:
  selector:
    app: revenue-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer