global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'revenue-calculator'
    static_configs:
      - targets: ['revenue-calculator:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s